#!/usr/bin/env python3
"""
gliner-server: optional sidecar for laya-mcp.

Thin HTTP wrapper around GLiNER2.5 (fastino/gliner2.5-multi-v1), a 287M
multilingual span-extraction model. It finds *where* things are in text
(entities with character offsets, relations, PII/secrets); Laya remains
the judge that decides *what they mean* with calibrated probabilities.

This process is 100% optional:
  - If it is not running, laya-mcp keeps working. `laya_extract` falls
    back to its regex path and `laya_pii` reports a clear error.
  - Start it with $HOME/laya-mcp/start_gliner.sh (generated by
    install.sh --with-gliner).

Default port 8766 (laya-server uses 8765).
"""
from __future__ import annotations

import asyncio
import logging
import os
import sys
import time
from typing import Any, Dict, List, Optional, Union

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

logging.basicConfig(
    level=os.getenv("GLINER_LOG_LEVEL", os.getenv("LAYA_LOG_LEVEL", "WARNING")),
    format="%(asctime)s [%(levelname)s] %(message)s",
    stream=sys.stderr,
)
log = logging.getLogger("gliner-server")

DEFAULT_MODEL = os.getenv("GLINER_MODEL", "fastino/gliner2.5-multi-v1")
DEFAULT_DEVICE_SETTING = os.getenv("GLINER_DEVICE", "auto")  # auto|cpu|cuda|mps

# Fixed label set for /pii_scan. Descriptions are short English phrases;
# the multilingual encoder handles Spanish text against them (verified).
PII_LABELS: Dict[str, str] = {
    "email": "Email addresses like name@domain.com",
    "telefono": "Phone numbers in any format, with or without country code",
    "api_key": "API keys and secrets starting with sk-, ghp_, AKIA, xox- and similar prefixes",
    "token_secreto": "Authentication tokens, bearer tokens and session secrets",
    "password": "Passwords and credentials",
    "persona": "Names of people",
}


def _resolve_device() -> str:
    req = DEFAULT_DEVICE_SETTING.lower()
    if req != "auto":
        return req
    try:
        import torch

        if torch.cuda.is_available():
            return "cuda"
        backends = getattr(torch, "backends", None)
        mps = getattr(getattr(backends, "mps", None), "is_available", None)
        if callable(mps) and mps():
            return "mps"
    except Exception:  # noqa: BLE001
        pass
    return "cpu"


class _ExtractorHolder:
    """Lazy GLiNER loader so the HTTP server boots even when weights are missing."""

    def __init__(self) -> None:
        self._model = None
        self._load_error: str | None = None
        self._device: str | None = None
        self._loaded_at: float | None = None

    def _ensure(self) -> Any:
        if self._model is not None:
            return self._model
        if self._load_error is not None:
            raise RuntimeError(self._load_error)
        try:
            from gliner2 import AutoExtractor

            device = _resolve_device()
            log.info("loading GLiNER model=%s device=%s", DEFAULT_MODEL, device)
            self._model = AutoExtractor.from_pretrained(DEFAULT_MODEL, map_location=device)
            self._device = device
            self._loaded_at = time.time()
            log.info("GLiNER ready: %s on %s", type(self._model).__name__, device)
        except Exception as exc:  # noqa: BLE001
            self._load_error = f"gliner not loaded: {exc!r}"
            log.exception("GLiNER load failed")
            raise
        return self._model

    def health(self) -> Dict[str, Any]:
        if self._model is None:
            try:
                self._ensure()
            except Exception as exc:  # noqa: BLE001
                return {"ready": False, "error": str(exc)}
        return {
            "ready": True,
            "model": DEFAULT_MODEL,
            "device": self._device,
            "uptime_seconds": (time.time() - self._loaded_at) if self._loaded_at else 0.0,
        }


holder = _ExtractorHolder()


# -- HTTP contract ----------------------------------------------------------

Labels = Union[List[str], Dict[str, str]]


class ExtractRequest(BaseModel):
    text: str = Field(..., description="Document text to extract from.")
    labels: Labels = Field(
        ...,
        description="Entity types: list of names or {name: description} map.",
    )
    include_spans: bool = True
    include_confidence: bool = True


class ClassifyRequest(BaseModel):
    text: str = Field(..., description="Text to classify.")
    tasks: Dict[str, Any] = Field(
        ...,
        description="Tasks map passed straight to classify_text, e.g. {\"intent\": [\"a\", \"b\"]}.",
    )


class PiiRequest(BaseModel):
    text: str = Field(..., description="Text to scan for PII and secrets.")
    extra_types: List[str] = Field(
        default_factory=list,
        description="Extra zero-shot entity types to look for alongside the PII set.",
    )


app = FastAPI(title="gliner-server", version="0.1.0")

# CORS is permissive because this process binds to 127.0.0.1 only.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health() -> Dict[str, Any]:
    """Liveness + readiness. Ensures the model is loaded, so first call warms up here."""
    return {"status": "ok", **holder.health()}


@app.get("/ready")
async def ready() -> Dict[str, Any]:
    info = holder.health()
    if not info.get("ready"):
        raise HTTPException(status_code=503, detail=info)
    return {"status": "ready", **info}


@app.post("/extract_entities")
async def extract_entities(req: ExtractRequest) -> Dict[str, Any]:
    """Zero-shot entity spans with character offsets. No regex required."""
    start = time.perf_counter()
    try:
        model = await asyncio.to_thread(holder._ensure)
        result = await asyncio.to_thread(
            model.extract_entities,
            req.text,
            req.labels,
            include_confidence=req.include_confidence,
            include_spans=req.include_spans,
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=f"extraction error: {exc!r}") from exc
    return {
        "entities": result.get("entities", result) if isinstance(result, dict) else result,
        "latency_ms": (time.perf_counter() - start) * 1000.0,
    }


@app.post("/classify")
async def classify(req: ClassifyRequest) -> Dict[str, Any]:
    """Zero-shot text classification. Tasks map is passed straight through."""
    start = time.perf_counter()
    try:
        model = await asyncio.to_thread(holder._ensure)
        result = await asyncio.to_thread(model.classify_text, req.text, req.tasks)
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=f"classification error: {exc!r}") from exc
    return {
        "result": result,
        "latency_ms": (time.perf_counter() - start) * 1000.0,
    }


@app.post("/pii_scan")
async def pii_scan(req: PiiRequest) -> Dict[str, Any]:
    """Scan for PII and secrets. Returns flat findings sorted by offset."""
    start = time.perf_counter()
    labels: Dict[str, str] = dict(PII_LABELS)
    for extra in req.extra_types or []:
        labels.setdefault(extra, extra.replace("_", " "))
    try:
        model = await asyncio.to_thread(holder._ensure)
        result = await asyncio.to_thread(
            model.extract_entities,
            req.text,
            labels,
            include_confidence=True,
            include_spans=True,
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=f"pii scan error: {exc!r}") from exc

    entities = result.get("entities", {}) if isinstance(result, dict) else {}
    findings: List[Dict[str, Any]] = []
    for etype, spans in entities.items():
        for s in spans or []:
            findings.append(
                {
                    "type": etype,
                    "text": s.get("text"),
                    "start": s.get("start"),
                    "end": s.get("end"),
                    "confidence": s.get("confidence", 0.0),
                }
            )
    findings.sort(key=lambda f: (f["start"] is None, f["start"] or 0))
    counts: Dict[str, int] = {}
    for f in findings:
        counts[f["type"]] = counts.get(f["type"], 0) + 1
    return {
        "findings": findings,
        "counts": counts,
        "latency_ms": (time.perf_counter() - start) * 1000.0,
    }


def main() -> None:
    import uvicorn

    host = os.getenv("GLINER_HOST", "127.0.0.1")
    port = int(os.getenv("GLINER_PORT", "8766"))
    log.info("gliner-server starting on http://%s:%d", host, port)
    uvicorn.run(app, host=host, port=port, log_level="warning")


if __name__ == "__main__":
    main()
